"use client";

import { useEffect,useState } from "react";
import "./profile.css";

type Goal="healthy"|"lose"|"maintain"|"gain"|"performance";
type Profile={name:string;age:number;height:number;weight:number;activity:"low"|"medium"|"high";goal:Goal;calories:number;protein:number;carbs:number;fat:number};
type Store={onboarded:boolean;profile:Profile;meals:unknown[];water:Record<string,number>};
const STORAGE_KEY="noura-beta-v01";
const fallback:Profile={name:"",age:23,height:175,weight:72,activity:"medium",goal:"healthy",calories:2300,protein:150,carbs:260,fat:75};
function calculateTargets(p:Profile){const a=p.activity==="low"?1.35:p.activity==="high"?1.7:1.5;let c=Math.round(((10*p.weight+6.25*p.height-5*p.age+5)*a)/50)*50;if(p.goal==="lose")c-=350;if(p.goal==="gain")c+=300;if(p.goal==="performance")c+=150;c=Math.max(1500,c);const protein=Math.round(p.weight*((p.goal==="gain"||p.goal==="performance")?2:1.8));const fat=Math.round(p.weight*.9);const carbs=Math.max(100,Math.round((c-protein*4-fat*9)/4));return{...p,calories:c,protein,carbs,fat};}

export default function ProfilePage(){
 const [profile,setProfile]=useState<Profile>(fallback);const [store,setStore]=useState<Store|null>(null);const [saved,setSaved]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const s=JSON.parse(raw);setStore(s);setProfile({...fallback,...s.profile});}}catch{}},[]);
 function save(recalculate=false){const nextProfile=recalculate?calculateTargets(profile):profile;const base=store||{onboarded:true,profile:nextProfile,meals:[],water:{}};const next={...base,profile:nextProfile};localStorage.setItem(STORAGE_KEY,JSON.stringify(next));setStore(next);setProfile(nextProfile);setSaved(true);window.setTimeout(()=>setSaved(false),1800);}
 return <main className="edit-profile-shell"><div className="edit-profile-wrap"><header className="edit-profile-top"><a href="/" className="coach-brand"><span>N</span><b>NOURA PROFILE</b></a><a href="/" className="coach-back">Volver</a></header><section className="edit-profile-hero"><div className="kicker">LOCAL PROFILE</div><h1>Edita tu perfil y tus objetivos.</h1><p>Estos datos permanecen guardados en este dispositivo. Puedes recalcular tus metas o definirlas manualmente.</p></section><section className="edit-profile-card"><div className="edit-profile-grid"><label><span>Nombre</span><input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label><span>Edad</span><input type="number" value={profile.age} onChange={e=>setProfile({...profile,age:Number(e.target.value)})}/></label><label><span>Peso (kg)</span><input type="number" value={profile.weight} onChange={e=>setProfile({...profile,weight:Number(e.target.value)})}/></label><label><span>Altura (cm)</span><input type="number" value={profile.height} onChange={e=>setProfile({...profile,height:Number(e.target.value)})}/></label><label><span>Actividad</span><select value={profile.activity} onChange={e=>setProfile({...profile,activity:e.target.value as Profile["activity"]})}><option value="low">Baja</option><option value="medium">Media</option><option value="high">Alta</option></select></label><label><span>Objetivo</span><select value={profile.goal} onChange={e=>setProfile({...profile,goal:e.target.value as Goal})}><option value="healthy">Comer mejor</option><option value="lose">Perder grasa</option><option value="maintain">Mantener</option><option value="gain">Ganar músculo</option><option value="performance">Rendimiento</option></select></label></div><div className="edit-profile-targets"><label><span>Calorías</span><input type="number" value={profile.calories} onChange={e=>setProfile({...profile,calories:Number(e.target.value)})}/></label><label><span>Proteína</span><input type="number" value={profile.protein} onChange={e=>setProfile({...profile,protein:Number(e.target.value)})}/></label><label><span>Carbs</span><input type="number" value={profile.carbs} onChange={e=>setProfile({...profile,carbs:Number(e.target.value)})}/></label><label><span>Grasas</span><input type="number" value={profile.fat} onChange={e=>setProfile({...profile,fat:Number(e.target.value)})}/></label></div><div className="edit-profile-actions"><button className="profile-secondary" onClick={()=>save(true)}>Recalcular metas</button><button className="profile-primary" onClick={()=>save(false)}>{saved?"Guardado ✓":"Guardar cambios"}</button></div></section><a className="profile-settings-link" href="/notifications"><div><span className="kicker">TELEGRAM</span><strong>Notificaciones inteligentes</strong><small>Comprueba conexión, recordatorios y envía una prueba.</small></div><b>→</b></a></div></main>;
}
